CREATE TABLE pvuser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    name       VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_pvuser PRIMARY KEY (id)
);

ALTER TABLE pvuser
    ADD CONSTRAINT uc_pvuser_email UNIQUE (email);